### ISSUE TITLE
Plugin does not have web implementation warning

### ISSUE THREAD

**Issue by mhartington** [robmarti/cap-bluetooth-low-energy-client#2]
Hi there! I'm looking to test out this plugin in chrome.
The plugin appears to support web target, but when I attempt to use the plugin, it throws an error 

```
core.js:9110 ERROR Error: Uncaught (in promise): BluetoothLEClient does not have web implementation
```
 
I'm guessing that the plugin is not exposed correctly?

**Comment by mhartington** [comment]
looks like the docs need to be updated
```
import { Component } from '@angular/core';
import { BluetoothLEClient } from 'cap-bluetooth-low-energy-client'

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss']
})
export class HomePage {
  constructor() {}
  // tslint:disable-next-line: use-lifecycle-interface
  async ngOnInit() {
    const isAvailable = await BluetoothLEClient.isAvailable();
  }
}
```

You should be importing from the plugin directly instead of calling it from the Capacitor Plugin Proxy.

**Comment by ghost** [comment]
Hi @mhartington ,
you are totally right. If you just want to use the web implementation, a direct import is the way to go.
However, when directly importing the plugin in a native context, it will not fall back on its native implementation. 
If you want a solution that works for all platforms you have to call it from the Plugin Proxy.

This way it should work for all platforms:
```
import 'cap-bluetooth-low-energy-client';
import {Plugins} from '@capacitor/core';

const {BluetoothLEClient} = Plugins;
```

Anyway, I'm going to update the docs as soon as possible 👍
