### ISSUE TITLE
iOS support update

### ISSUE THREAD

**Issue by Francois-Belanger** [robmarti/cap-bluetooth-low-energy-client#3]
Hi, I see that you started the iOS.  What is the current state ?

Thanks

**Comment by ghost** [comment]
Hi @Francois-Belanger , all the iOS related resources are auto-generated. I have no experience in Swift/Objective-C programming or iOS development in general, let alone an iOS device for testing purposes. So the current state is that there is no iOS implementation.
I was hoping that maybe someone with more experience in iOS development could contribute to this project 😄

**Comment by Francois-Belanger** [comment]
I would love to.  But I don't have time for now.  I will keep a note :-)
